# Usa una imagen base de Python
FROM python:3.12


#RUN apt-get update && apt-get install -y 



# Establece el directorio de trabajo
WORKDIR /app

# Copia los archivos necesarios
COPY . /app

    
# Expon el puerto en el que corre tu servidor gRPC
EXPOSE 50051

# Comando para ejecutar tu servidor
#CMD ["python3", "consumer.py"]
