# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: orders.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'orders.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0corders.proto\"\x97\x01\n\x05Order\x12\x14\n\x0cproduct_name\x18\x01 \x01(\t\x12\r\n\x05price\x18\x02 \x01(\x02\x12\x17\n\x0fpayment_gateway\x18\x03 \x01(\t\x12\x12\n\ncard_brand\x18\x04 \x01(\t\x12\x0c\n\x04\x62\x61nk\x18\x05 \x01(\t\x12\x0e\n\x06region\x18\x06 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x07 \x01(\t\x12\r\n\x05\x65mail\x18\x08 \x01(\t\"1\n\rOrderResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x10\n\x08order_id\x18\x02 \x01(\t28\n\x0fOrderManagement\x12%\n\x0b\x43reateOrder\x12\x06.Order\x1a\x0e.OrderResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'orders_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ORDER']._serialized_start=17
  _globals['_ORDER']._serialized_end=168
  _globals['_ORDERRESPONSE']._serialized_start=170
  _globals['_ORDERRESPONSE']._serialized_end=219
  _globals['_ORDERMANAGEMENT']._serialized_start=221
  _globals['_ORDERMANAGEMENT']._serialized_end=277
# @@protoc_insertion_point(module_scope)
